# Generated by Django 5.2.9 on 2025-12-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ai_analysis_data',
            field=models.JSONField(blank=True, help_text='AI analysis output for audit', null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence level', null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='compliance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_key',
            field=models.CharField(blank=True, db_index=True, help_text='Hash for idempotent imports', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='normalized_frequency',
            field=models.CharField(blank=True, help_text='AI-normalized frequency: Daily, Weekly, Monthly, Quarterly, Annual, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='indicator',
            name='schedule_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='score',
            field=models.IntegerField(default=10, help_text='Score awarded when compliant'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='area',
            field=models.CharField(blank=True, help_text='Legacy field, use Section model instead', max_length=255),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Email or username', max_length=255),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='frequency',
            field=models.CharField(blank=True, help_text='Original frequency text from CSV', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='regulation_or_standard',
            field=models.CharField(blank=True, help_text='Legacy field, use Standard model instead', max_length=255),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='status',
            field=models.CharField(choices=[('not_compliant', 'Not Compliant'), ('in_process', 'In Process'), ('needs_more_evidence', 'Needs More Evidence'), ('compliant', 'Compliant'), ('pending', 'Pending'), ('partial', 'Partial'), ('non_compliant', 'Non-Compliant')], default='not_compliant', max_length=25),
        ),
        migrations.CreateModel(
            name='IndicatorStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.indicator')),
            ],
            options={
                'verbose_name_plural': 'Indicator Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='api.section'),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='api.section')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='api.standard'),
        ),
        migrations.CreateModel(
            name='FrequencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_compliant', models.BooleanField(default=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_logs', to='api.indicator')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('indicator', 'period_start', 'period_end')},
            },
        ),
    ]
