# Generated by Django 5.0.6 on 2025-12-19 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_evidence_uploaded_by_indicator_ai_analysis_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="evidence_text",
            field=models.TextField(
                blank=True,
                help_text="Text declaration for physical evidence",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="evidence_type",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("text_declaration", "Text Declaration"),
                    ("hybrid", "Hybrid"),
                    ("form_submission", "Form Submission"),
                ],
                default="file",
                help_text="Type of evidence",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="form_data",
            field=models.JSONField(
                blank=True, help_text="Form submission data", null=True
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="google_drive_file_id",
            field=models.CharField(
                blank=True, help_text="Google Drive file ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="google_drive_file_name",
            field=models.CharField(
                blank=True,
                help_text="Google Drive file name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="google_drive_file_url",
            field=models.URLField(
                blank=True, help_text="Google Drive sharing link", null=True
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="period_end",
            field=models.DateField(
                blank=True,
                help_text="Period end date for frequency-based evidence",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="period_start",
            field=models.DateField(
                blank=True,
                help_text="Period start date for frequency-based evidence",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="evidence_mode",
            field=models.CharField(
                choices=[
                    ("file_only", "File Only"),
                    ("text_only", "Text Only"),
                    ("hybrid", "Hybrid (Text + Optional File)"),
                    ("frequency_log", "Frequency Log"),
                ],
                default="hybrid",
                help_text="How evidence is expected for this indicator",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="indicator_code",
            field=models.CharField(
                blank=True,
                help_text="Code for folder naming (e.g., 'IND-001')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="google_drive_linked_at",
            field=models.DateTimeField(
                blank=True, help_text="When Google Drive was linked", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="google_drive_oauth_token",
            field=models.JSONField(
                blank=True,
                help_text="OAuth token data for Google Drive access",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="google_drive_root_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Google Drive root folder ID for this project",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="DEPRECATED: Use Google Drive instead",
                null=True,
                upload_to="evidence/",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="url",
            field=models.URLField(
                blank=True, help_text="DEPRECATED: Use google_drive_file_url instead"
            ),
        ),
        migrations.CreateModel(
            name="DigitalFormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "form_fields",
                    models.JSONField(help_text="Field definitions for the form"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_form_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_templates",
                        to="api.indicator",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="evidence",
            name="form_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Form template used for this submission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="api.digitalformtemplate",
            ),
        ),
        migrations.CreateModel(
            name="EvidencePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "expected_evidence_count",
                    models.IntegerField(
                        default=1,
                        help_text="Expected number of evidence entries for this period",
                    ),
                ),
                (
                    "actual_evidence_count",
                    models.IntegerField(
                        default=0,
                        help_text="Actual number of evidence entries (computed)",
                    ),
                ),
                (
                    "is_compliant",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this period is compliant (computed)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_periods",
                        to="api.indicator",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("indicator", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="GoogleDriveFolderCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_path",
                    models.CharField(
                        help_text="Path like 'Section/Standard/Indicator'",
                        max_length=500,
                    ),
                ),
                (
                    "google_drive_folder_id",
                    models.CharField(
                        help_text="Google Drive folder ID", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_folder_cache",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("project", "folder_path")},
            },
        ),
    ]
