# Generated by Django 5.0.6 on 2025-12-19 11:37

import django.db.models.deletion
from django.db import migrations, models


def populate_evidence_project(apps, schema_editor):
    """Populate project field from indicator's project for existing evidence."""
    Evidence = apps.get_model('api', 'Evidence')
    for evidence in Evidence.objects.filter(project__isnull=True):
        if evidence.indicator and evidence.indicator.project:
            evidence.project = evidence.indicator.project
            evidence.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_evidence_library_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="drive_file_id",
            field=models.CharField(
                blank=True, help_text="Google Drive file ID", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="drive_mime_type",
            field=models.CharField(
                blank=True, help_text="MIME type of the file", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="drive_web_view_link",
            field=models.URLField(
                blank=True, help_text="Google Drive web view link", null=True
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename before upload",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this evidence belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="storage",
            field=models.CharField(
                choices=[("local", "Local"), ("gdrive", "Google Drive")],
                default="local",
                help_text="Storage location for this evidence",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drive_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Google Drive root folder ID for this project",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drive_linked_at",
            field=models.DateTimeField(
                blank=True, help_text="When Google Drive was linked", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drive_linked_email",
            field=models.CharField(
                blank=True,
                help_text="Email of user who linked Drive",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="evidence_storage_mode",
            field=models.CharField(
                choices=[("local", "Local"), ("gdrive", "Google Drive")],
                default="local",
                help_text="Storage mode for evidence files",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="google_drive_file_id",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use drive_file_id instead",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="google_drive_file_name",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use original_filename instead",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="google_drive_file_url",
            field=models.URLField(
                blank=True,
                help_text="DEPRECATED: Use drive_web_view_link instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="indicator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="api.indicator",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="google_drive_linked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="DEPRECATED: Use drive_linked_at instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="google_drive_oauth_token",
            field=models.JSONField(
                blank=True,
                help_text="DEPRECATED: OAuth tokens no longer stored in backend",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="google_drive_root_folder_id",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use drive_folder_id instead",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(populate_evidence_project, migrations.RunPython.noop),
    ]
